### ISSUE TITLE
Would you consider a commercial-friendly license?

### ISSUE THREAD

**Issue by sailorfred** [bradsacks99/pyvalve#2]
Such as MIT, Apache, or BSD?

**Comment by bradsacks99** [comment]
I would consider it. Can you give me an idea of your use case and concerns with GPLv3?

**Comment by sailorfred** [comment]
Thanks for the extremely quick response!

The company I work for is probably similar to many.  We're a small ~100 employee company providing a SaaS service.  A small part of our system needs to do AV on user provided files.

We are in the process of rearchitecting that part of the service to use async.  This means we would like an async clam client.  Our security folks want us to run the clamd on a unix domain socket, not over TCP/IP.

Our current options are:

- Implement our own client
- Persuade you to change your license
- Work with or clone aioclamd to allow a socket option

Our legal advisors are allergic to the idea of GPL, and are busy enough they don't want to explore the differences between LGPL, GPL, and AGPL.  We are probably not alone in this attitude.

Thanks for your consideration!

**Comment by bradsacks99** [comment]
Ok, I get it. I've been in the same position once or twice. I'm happy that you might find PyValve useful. I'll change the license in the next 24 hours.
